### ISSUE TITLE
Is this still in development?

### ISSUE THREAD

**Issue by dcinzona** [paynecrl97/Glimpse.Orchard#10]
It looked great on the demo during the steering committee call, but I haven't seen any additional development done to this since then.  Has this gone stale?

**Comment by Ermesx** [comment]
+1

**Comment by Hazzamanic** [comment]
bump

**Comment by Hazzamanic** [comment]
https://github.com/BedeGaming/Glimpse.Orchard seems development is now on his company's (I assume?) branch

**Comment by paynecrl97** [comment]
I'm in the process of moving it into the core Orchard codebase, so focus has been switched away from this repo.

That said, @Hazzamanic is correct in stating that we have a fork that we use internally, which is still being updated as and when we have a need to.

You can follow the issue here: https://github.com/OrchardCMS/Orchard/issues/5419

And the branch I am currently working on is: https://github.com/paynecrl97/Orchard/tree/feature/glimpse

**Comment by dcinzona** [comment]
Awesome, thanks!
